// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.3
// source: pkg/proto/_fetch_search_index.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlightSearchData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reg           string                 `protobuf:"bytes,1,opt,name=reg,proto3" json:"reg,omitempty"`
	SchdFrom      string                 `protobuf:"bytes,2,opt,name=schd_from,json=schdFrom,proto3" json:"schd_from,omitempty"`
	SchdTo        string                 `protobuf:"bytes,3,opt,name=schd_to,json=schdTo,proto3" json:"schd_to,omitempty"`
	Flight        string                 `protobuf:"bytes,4,opt,name=flight,proto3" json:"flight,omitempty"`
	Operator      string                 `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	AcType        string                 `protobuf:"bytes,6,opt,name=ac_type,json=acType,proto3" json:"ac_type,omitempty"`
	Lat           float32                `protobuf:"fixed32,7,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float32                `protobuf:"fixed32,8,opt,name=lon,proto3" json:"lon,omitempty"`
	Callsign      string                 `protobuf:"bytes,9,opt,name=callsign,proto3" json:"callsign,omitempty"`
	Id            uint32                 `protobuf:"varint,10,opt,name=id,proto3" json:"id,omitempty"`
	Restricted    bool                   `protobuf:"varint,11,opt,name=restricted,proto3" json:"restricted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlightSearchData) Reset() {
	*x = FlightSearchData{}
	mi := &file_fr24_proto__fetch_search_index_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightSearchData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightSearchData) ProtoMessage() {}

func (x *FlightSearchData) ProtoReflect() protoreflect.Message {
	mi := &file_fr24_proto__fetch_search_index_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightSearchData.ProtoReflect.Descriptor instead.
func (*FlightSearchData) Descriptor() ([]byte, []int) {
	return file_fr24_proto__fetch_search_index_proto_rawDescGZIP(), []int{0}
}

func (x *FlightSearchData) GetReg() string {
	if x != nil {
		return x.Reg
	}
	return ""
}

func (x *FlightSearchData) GetSchdFrom() string {
	if x != nil {
		return x.SchdFrom
	}
	return ""
}

func (x *FlightSearchData) GetSchdTo() string {
	if x != nil {
		return x.SchdTo
	}
	return ""
}

func (x *FlightSearchData) GetFlight() string {
	if x != nil {
		return x.Flight
	}
	return ""
}

func (x *FlightSearchData) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *FlightSearchData) GetAcType() string {
	if x != nil {
		return x.AcType
	}
	return ""
}

func (x *FlightSearchData) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *FlightSearchData) GetLon() float32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *FlightSearchData) GetCallsign() string {
	if x != nil {
		return x.Callsign
	}
	return ""
}

func (x *FlightSearchData) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FlightSearchData) GetRestricted() bool {
	if x != nil {
		return x.Restricted
	}
	return false
}

type FetchSearchIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchSearchIndexRequest) Reset() {
	*x = FetchSearchIndexRequest{}
	mi := &file_fr24_proto__fetch_search_index_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchSearchIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSearchIndexRequest) ProtoMessage() {}

func (x *FetchSearchIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fr24_proto__fetch_search_index_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSearchIndexRequest.ProtoReflect.Descriptor instead.
func (*FetchSearchIndexRequest) Descriptor() ([]byte, []int) {
	return file_fr24_proto__fetch_search_index_proto_rawDescGZIP(), []int{1}
}

type FetchSearchIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightsList   []*FlightSearchData    `protobuf:"bytes,1,rep,name=flights_list,json=flightsList,proto3" json:"flights_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchSearchIndexResponse) Reset() {
	*x = FetchSearchIndexResponse{}
	mi := &file_fr24_proto__fetch_search_index_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchSearchIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSearchIndexResponse) ProtoMessage() {}

func (x *FetchSearchIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fr24_proto__fetch_search_index_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSearchIndexResponse.ProtoReflect.Descriptor instead.
func (*FetchSearchIndexResponse) Descriptor() ([]byte, []int) {
	return file_fr24_proto__fetch_search_index_proto_rawDescGZIP(), []int{2}
}

func (x *FetchSearchIndexResponse) GetFlightsList() []*FlightSearchData {
	if x != nil {
		return x.FlightsList
	}
	return nil
}

var File_fr24_proto__fetch_search_index_proto protoreflect.FileDescriptor

const file_fr24_proto__fetch_search_index_proto_rawDesc = "" +
	"\n" +
	"$fr24/proto/_fetch_search_index.proto\x12\x10fr24.feed.api.v1\"\x97\x02\n" +
	"\x10FlightSearchData\x12\x10\n" +
	"\x03reg\x18\x01 \x01(\tR\x03reg\x12\x1b\n" +
	"\tschd_from\x18\x02 \x01(\tR\bschdFrom\x12\x17\n" +
	"\aschd_to\x18\x03 \x01(\tR\x06schdTo\x12\x16\n" +
	"\x06flight\x18\x04 \x01(\tR\x06flight\x12\x1a\n" +
	"\boperator\x18\x05 \x01(\tR\boperator\x12\x17\n" +
	"\aac_type\x18\x06 \x01(\tR\x06acType\x12\x10\n" +
	"\x03lat\x18\a \x01(\x02R\x03lat\x12\x10\n" +
	"\x03lon\x18\b \x01(\x02R\x03lon\x12\x1a\n" +
	"\bcallsign\x18\t \x01(\tR\bcallsign\x12\x0e\n" +
	"\x02id\x18\n" +
	" \x01(\rR\x02id\x12\x1e\n" +
	"\n" +
	"restricted\x18\v \x01(\bR\n" +
	"restricted\"\x19\n" +
	"\x17FetchSearchIndexRequest\"a\n" +
	"\x18FetchSearchIndexResponse\x12E\n" +
	"\fflights_list\x18\x01 \x03(\v2\".fr24.feed.api.v1.FlightSearchDataR\vflightsListB0Z.github.com/igolaizola/flightradar24/fr24/protob\x06proto3"

var (
	file_fr24_proto__fetch_search_index_proto_rawDescOnce sync.Once
	file_fr24_proto__fetch_search_index_proto_rawDescData []byte
)

func file_fr24_proto__fetch_search_index_proto_rawDescGZIP() []byte {
	file_fr24_proto__fetch_search_index_proto_rawDescOnce.Do(func() {
		file_fr24_proto__fetch_search_index_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fr24_proto__fetch_search_index_proto_rawDesc), len(file_fr24_proto__fetch_search_index_proto_rawDesc)))
	})
	return file_fr24_proto__fetch_search_index_proto_rawDescData
}

var file_fr24_proto__fetch_search_index_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_fr24_proto__fetch_search_index_proto_goTypes = []any{
	(*FlightSearchData)(nil),         // 0: fr24.feed.api.v1.FlightSearchData
	(*FetchSearchIndexRequest)(nil),  // 1: fr24.feed.api.v1.FetchSearchIndexRequest
	(*FetchSearchIndexResponse)(nil), // 2: fr24.feed.api.v1.FetchSearchIndexResponse
}
var file_fr24_proto__fetch_search_index_proto_depIdxs = []int32{
	0, // 0: fr24.feed.api.v1.FetchSearchIndexResponse.flights_list:type_name -> fr24.feed.api.v1.FlightSearchData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fr24_proto__fetch_search_index_proto_init() }
func file_fr24_proto__fetch_search_index_proto_init() {
	if File_fr24_proto__fetch_search_index_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fr24_proto__fetch_search_index_proto_rawDesc), len(file_fr24_proto__fetch_search_index_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fr24_proto__fetch_search_index_proto_goTypes,
		DependencyIndexes: file_fr24_proto__fetch_search_index_proto_depIdxs,
		MessageInfos:      file_fr24_proto__fetch_search_index_proto_msgTypes,
	}.Build()
	File_fr24_proto__fetch_search_index_proto = out.File
	file_fr24_proto__fetch_search_index_proto_goTypes = nil
	file_fr24_proto__fetch_search_index_proto_depIdxs = nil
}
