// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.3
// source: pkg/proto/_health.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             uint32                 `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B             uint32                 `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_fr24_proto__health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_fr24_proto__health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_fr24_proto__health_proto_rawDescGZIP(), []int{0}
}

func (x *Ping) GetA() uint32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *Ping) GetB() uint32 {
	if x != nil {
		return x.B
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C             uint32                 `protobuf:"varint,1,opt,name=c,proto3" json:"c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_fr24_proto__health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_fr24_proto__health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_fr24_proto__health_proto_rawDescGZIP(), []int{1}
}

func (x *Pong) GetC() uint32 {
	if x != nil {
		return x.C
	}
	return 0
}

var File_fr24_proto__health_proto protoreflect.FileDescriptor

const file_fr24_proto__health_proto_rawDesc = "" +
	"\n" +
	"\x18fr24/proto/_health.proto\x12\x10fr24.feed.api.v1\"\"\n" +
	"\x04Ping\x12\f\n" +
	"\x01a\x18\x01 \x01(\rR\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\rR\x01b\"\x14\n" +
	"\x04Pong\x12\f\n" +
	"\x01c\x18\x01 \x01(\rR\x01cB0Z.github.com/igolaizola/flightradar24/fr24/protob\x06proto3"

var (
	file_fr24_proto__health_proto_rawDescOnce sync.Once
	file_fr24_proto__health_proto_rawDescData []byte
)

func file_fr24_proto__health_proto_rawDescGZIP() []byte {
	file_fr24_proto__health_proto_rawDescOnce.Do(func() {
		file_fr24_proto__health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fr24_proto__health_proto_rawDesc), len(file_fr24_proto__health_proto_rawDesc)))
	})
	return file_fr24_proto__health_proto_rawDescData
}

var file_fr24_proto__health_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fr24_proto__health_proto_goTypes = []any{
	(*Ping)(nil), // 0: fr24.feed.api.v1.Ping
	(*Pong)(nil), // 1: fr24.feed.api.v1.Pong
}
var file_fr24_proto__health_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fr24_proto__health_proto_init() }
func file_fr24_proto__health_proto_init() {
	if File_fr24_proto__health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fr24_proto__health_proto_rawDesc), len(file_fr24_proto__health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fr24_proto__health_proto_goTypes,
		DependencyIndexes: file_fr24_proto__health_proto_depIdxs,
		MessageInfos:      file_fr24_proto__health_proto_msgTypes,
	}.Build()
	File_fr24_proto__health_proto = out.File
	file_fr24_proto__health_proto_goTypes = nil
	file_fr24_proto__health_proto_depIdxs = nil
}
