// NOTE: the definition in the web client is:
// ```
// message LiveFlightsStatusResponse {
//     repeated LiveFlightStatusData flights_map = 1;
// }
// ```
// but in reality it returns a wrapped `LiveFlightStatusData`.
// the names `LiveFlightStatus`, `flight_id` and `data`
// are non-official.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.3
// source: pkg/proto/_live_flight_status.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LiveFlightStatusData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float32                `protobuf:"fixed32,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float32                `protobuf:"fixed32,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Status        Status                 `protobuf:"varint,3,opt,name=status,proto3,enum=_common.Status" json:"status,omitempty"`
	Squawk        uint32                 `protobuf:"varint,4,opt,name=squawk,proto3" json:"squawk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveFlightStatusData) Reset() {
	*x = LiveFlightStatusData{}
	mi := &file_fr24_proto__live_flight_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveFlightStatusData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveFlightStatusData) ProtoMessage() {}

func (x *LiveFlightStatusData) ProtoReflect() protoreflect.Message {
	mi := &file_fr24_proto__live_flight_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveFlightStatusData.ProtoReflect.Descriptor instead.
func (*LiveFlightStatusData) Descriptor() ([]byte, []int) {
	return file_fr24_proto__live_flight_status_proto_rawDescGZIP(), []int{0}
}

func (x *LiveFlightStatusData) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *LiveFlightStatusData) GetLon() float32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *LiveFlightStatusData) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_NORMAL
}

func (x *LiveFlightStatusData) GetSquawk() uint32 {
	if x != nil {
		return x.Squawk
	}
	return 0
}

type LiveFlightsStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightIdsList []uint32               `protobuf:"fixed32,1,rep,packed,name=flight_ids_list,json=flightIdsList,proto3" json:"flight_ids_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveFlightsStatusRequest) Reset() {
	*x = LiveFlightsStatusRequest{}
	mi := &file_fr24_proto__live_flight_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveFlightsStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveFlightsStatusRequest) ProtoMessage() {}

func (x *LiveFlightsStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fr24_proto__live_flight_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveFlightsStatusRequest.ProtoReflect.Descriptor instead.
func (*LiveFlightsStatusRequest) Descriptor() ([]byte, []int) {
	return file_fr24_proto__live_flight_status_proto_rawDescGZIP(), []int{1}
}

func (x *LiveFlightsStatusRequest) GetFlightIdsList() []uint32 {
	if x != nil {
		return x.FlightIdsList
	}
	return nil
}

type LiveFlightStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightId      uint32                 `protobuf:"varint,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	Data          *LiveFlightStatusData  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveFlightStatus) Reset() {
	*x = LiveFlightStatus{}
	mi := &file_fr24_proto__live_flight_status_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveFlightStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveFlightStatus) ProtoMessage() {}

func (x *LiveFlightStatus) ProtoReflect() protoreflect.Message {
	mi := &file_fr24_proto__live_flight_status_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveFlightStatus.ProtoReflect.Descriptor instead.
func (*LiveFlightStatus) Descriptor() ([]byte, []int) {
	return file_fr24_proto__live_flight_status_proto_rawDescGZIP(), []int{2}
}

func (x *LiveFlightStatus) GetFlightId() uint32 {
	if x != nil {
		return x.FlightId
	}
	return 0
}

func (x *LiveFlightStatus) GetData() *LiveFlightStatusData {
	if x != nil {
		return x.Data
	}
	return nil
}

type LiveFlightsStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightsMap    []*LiveFlightStatus    `protobuf:"bytes,1,rep,name=flights_map,json=flightsMap,proto3" json:"flights_map,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveFlightsStatusResponse) Reset() {
	*x = LiveFlightsStatusResponse{}
	mi := &file_fr24_proto__live_flight_status_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveFlightsStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveFlightsStatusResponse) ProtoMessage() {}

func (x *LiveFlightsStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fr24_proto__live_flight_status_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveFlightsStatusResponse.ProtoReflect.Descriptor instead.
func (*LiveFlightsStatusResponse) Descriptor() ([]byte, []int) {
	return file_fr24_proto__live_flight_status_proto_rawDescGZIP(), []int{3}
}

func (x *LiveFlightsStatusResponse) GetFlightsMap() []*LiveFlightStatus {
	if x != nil {
		return x.FlightsMap
	}
	return nil
}

var File_fr24_proto__live_flight_status_proto protoreflect.FileDescriptor

const file_fr24_proto__live_flight_status_proto_rawDesc = "" +
	"\n" +
	"$fr24/proto/_live_flight_status.proto\x12\x10fr24.feed.api.v1\x1a\x18fr24/proto/_common.proto\"{\n" +
	"\x14LiveFlightStatusData\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x02R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x02R\x03lon\x12'\n" +
	"\x06status\x18\x03 \x01(\x0e2\x0f._common.StatusR\x06status\x12\x16\n" +
	"\x06squawk\x18\x04 \x01(\rR\x06squawk\"B\n" +
	"\x18LiveFlightsStatusRequest\x12&\n" +
	"\x0fflight_ids_list\x18\x01 \x03(\aR\rflightIdsList\"k\n" +
	"\x10LiveFlightStatus\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\rR\bflightId\x12:\n" +
	"\x04data\x18\x02 \x01(\v2&.fr24.feed.api.v1.LiveFlightStatusDataR\x04data\"`\n" +
	"\x19LiveFlightsStatusResponse\x12C\n" +
	"\vflights_map\x18\x01 \x03(\v2\".fr24.feed.api.v1.LiveFlightStatusR\n" +
	"flightsMapB0Z.github.com/igolaizola/flightradar24/fr24/protob\x06proto3"

var (
	file_fr24_proto__live_flight_status_proto_rawDescOnce sync.Once
	file_fr24_proto__live_flight_status_proto_rawDescData []byte
)

func file_fr24_proto__live_flight_status_proto_rawDescGZIP() []byte {
	file_fr24_proto__live_flight_status_proto_rawDescOnce.Do(func() {
		file_fr24_proto__live_flight_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fr24_proto__live_flight_status_proto_rawDesc), len(file_fr24_proto__live_flight_status_proto_rawDesc)))
	})
	return file_fr24_proto__live_flight_status_proto_rawDescData
}

var file_fr24_proto__live_flight_status_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_fr24_proto__live_flight_status_proto_goTypes = []any{
	(*LiveFlightStatusData)(nil),      // 0: fr24.feed.api.v1.LiveFlightStatusData
	(*LiveFlightsStatusRequest)(nil),  // 1: fr24.feed.api.v1.LiveFlightsStatusRequest
	(*LiveFlightStatus)(nil),          // 2: fr24.feed.api.v1.LiveFlightStatus
	(*LiveFlightsStatusResponse)(nil), // 3: fr24.feed.api.v1.LiveFlightsStatusResponse
	(Status)(0),                       // 4: _common.Status
}
var file_fr24_proto__live_flight_status_proto_depIdxs = []int32{
	4, // 0: fr24.feed.api.v1.LiveFlightStatusData.status:type_name -> _common.Status
	0, // 1: fr24.feed.api.v1.LiveFlightStatus.data:type_name -> fr24.feed.api.v1.LiveFlightStatusData
	2, // 2: fr24.feed.api.v1.LiveFlightsStatusResponse.flights_map:type_name -> fr24.feed.api.v1.LiveFlightStatus
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_fr24_proto__live_flight_status_proto_init() }
func file_fr24_proto__live_flight_status_proto_init() {
	if File_fr24_proto__live_flight_status_proto != nil {
		return
	}
	file_fr24_proto__common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fr24_proto__live_flight_status_proto_rawDesc), len(file_fr24_proto__live_flight_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fr24_proto__live_flight_status_proto_goTypes,
		DependencyIndexes: file_fr24_proto__live_flight_status_proto_depIdxs,
		MessageInfos:      file_fr24_proto__live_flight_status_proto_msgTypes,
	}.Build()
	File_fr24_proto__live_flight_status_proto = out.File
	file_fr24_proto__live_flight_status_proto_goTypes = nil
	file_fr24_proto__live_flight_status_proto_depIdxs = nil
}
