// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.3
// source: pkg/proto/_live_trail.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LiveTrailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightId      uint32                 `protobuf:"fixed32,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveTrailRequest) Reset() {
	*x = LiveTrailRequest{}
	mi := &file_fr24_proto__live_trail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveTrailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveTrailRequest) ProtoMessage() {}

func (x *LiveTrailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fr24_proto__live_trail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveTrailRequest.ProtoReflect.Descriptor instead.
func (*LiveTrailRequest) Descriptor() ([]byte, []int) {
	return file_fr24_proto__live_trail_proto_rawDescGZIP(), []int{0}
}

func (x *LiveTrailRequest) GetFlightId() uint32 {
	if x != nil {
		return x.FlightId
	}
	return 0
}

type LiveTrailResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RadarRecordsList []*RadarHistoryRecord  `protobuf:"bytes,1,rep,name=radar_records_list,json=radarRecordsList,proto3" json:"radar_records_list,omitempty"` // ?
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LiveTrailResponse) Reset() {
	*x = LiveTrailResponse{}
	mi := &file_fr24_proto__live_trail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveTrailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveTrailResponse) ProtoMessage() {}

func (x *LiveTrailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fr24_proto__live_trail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveTrailResponse.ProtoReflect.Descriptor instead.
func (*LiveTrailResponse) Descriptor() ([]byte, []int) {
	return file_fr24_proto__live_trail_proto_rawDescGZIP(), []int{1}
}

func (x *LiveTrailResponse) GetRadarRecordsList() []*RadarHistoryRecord {
	if x != nil {
		return x.RadarRecordsList
	}
	return nil
}

var File_fr24_proto__live_trail_proto protoreflect.FileDescriptor

const file_fr24_proto__live_trail_proto_rawDesc = "" +
	"\n" +
	"\x1cfr24/proto/_live_trail.proto\x12\x10fr24.feed.api.v1\x1a\x18fr24/proto/_common.proto\"/\n" +
	"\x10LiveTrailRequest\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\aR\bflightId\"^\n" +
	"\x11LiveTrailResponse\x12I\n" +
	"\x12radar_records_list\x18\x01 \x03(\v2\x1b._common.RadarHistoryRecordR\x10radarRecordsListB0Z.github.com/igolaizola/flightradar24/fr24/protob\x06proto3"

var (
	file_fr24_proto__live_trail_proto_rawDescOnce sync.Once
	file_fr24_proto__live_trail_proto_rawDescData []byte
)

func file_fr24_proto__live_trail_proto_rawDescGZIP() []byte {
	file_fr24_proto__live_trail_proto_rawDescOnce.Do(func() {
		file_fr24_proto__live_trail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fr24_proto__live_trail_proto_rawDesc), len(file_fr24_proto__live_trail_proto_rawDesc)))
	})
	return file_fr24_proto__live_trail_proto_rawDescData
}

var file_fr24_proto__live_trail_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fr24_proto__live_trail_proto_goTypes = []any{
	(*LiveTrailRequest)(nil),   // 0: fr24.feed.api.v1.LiveTrailRequest
	(*LiveTrailResponse)(nil),  // 1: fr24.feed.api.v1.LiveTrailResponse
	(*RadarHistoryRecord)(nil), // 2: _common.RadarHistoryRecord
}
var file_fr24_proto__live_trail_proto_depIdxs = []int32{
	2, // 0: fr24.feed.api.v1.LiveTrailResponse.radar_records_list:type_name -> _common.RadarHistoryRecord
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fr24_proto__live_trail_proto_init() }
func file_fr24_proto__live_trail_proto_init() {
	if File_fr24_proto__live_trail_proto != nil {
		return
	}
	file_fr24_proto__common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fr24_proto__live_trail_proto_rawDesc), len(file_fr24_proto__live_trail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fr24_proto__live_trail_proto_goTypes,
		DependencyIndexes: file_fr24_proto__live_trail_proto_depIdxs,
		MessageInfos:      file_fr24_proto__live_trail_proto_msgTypes,
	}.Build()
	File_fr24_proto__live_trail_proto = out.File
	file_fr24_proto__live_trail_proto_goTypes = nil
	file_fr24_proto__live_trail_proto_depIdxs = nil
}
