// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.3
// source: pkg/proto/_nearest_flights.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Geolocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float32                `protobuf:"fixed32,1,opt,name=lat,proto3" json:"lat,omitempty"` // Latitude, degrees, -90 to 90
	Lon           float32                `protobuf:"fixed32,2,opt,name=lon,proto3" json:"lon,omitempty"` // Longitude, degrees, -180 to 180
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Geolocation) Reset() {
	*x = Geolocation{}
	mi := &file_fr24_proto__nearest_flights_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Geolocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Geolocation) ProtoMessage() {}

func (x *Geolocation) ProtoReflect() protoreflect.Message {
	mi := &file_fr24_proto__nearest_flights_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Geolocation.ProtoReflect.Descriptor instead.
func (*Geolocation) Descriptor() ([]byte, []int) {
	return file_fr24_proto__nearest_flights_proto_rawDescGZIP(), []int{0}
}

func (x *Geolocation) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Geolocation) GetLon() float32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type NearestFlightsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *Geolocation           `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Radius        uint32                 `protobuf:"varint,2,opt,name=radius,proto3" json:"radius,omitempty"` // Radius, metres
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`   // Maximum number of aircraft to return
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearestFlightsRequest) Reset() {
	*x = NearestFlightsRequest{}
	mi := &file_fr24_proto__nearest_flights_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearestFlightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearestFlightsRequest) ProtoMessage() {}

func (x *NearestFlightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fr24_proto__nearest_flights_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearestFlightsRequest.ProtoReflect.Descriptor instead.
func (*NearestFlightsRequest) Descriptor() ([]byte, []int) {
	return file_fr24_proto__nearest_flights_proto_rawDescGZIP(), []int{1}
}

func (x *NearestFlightsRequest) GetLocation() *Geolocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *NearestFlightsRequest) GetRadius() uint32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *NearestFlightsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type NearbyFlight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flight        *Flight                `protobuf:"bytes,1,opt,name=flight,proto3" json:"flight,omitempty"`
	Distance      uint32                 `protobuf:"varint,2,opt,name=distance,proto3" json:"distance,omitempty"` // Distance from the location, metres
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearbyFlight) Reset() {
	*x = NearbyFlight{}
	mi := &file_fr24_proto__nearest_flights_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearbyFlight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyFlight) ProtoMessage() {}

func (x *NearbyFlight) ProtoReflect() protoreflect.Message {
	mi := &file_fr24_proto__nearest_flights_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyFlight.ProtoReflect.Descriptor instead.
func (*NearbyFlight) Descriptor() ([]byte, []int) {
	return file_fr24_proto__nearest_flights_proto_rawDescGZIP(), []int{2}
}

func (x *NearbyFlight) GetFlight() *Flight {
	if x != nil {
		return x.Flight
	}
	return nil
}

func (x *NearbyFlight) GetDistance() uint32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

type NearestFlightsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightsList   []*NearbyFlight        `protobuf:"bytes,1,rep,name=flights_list,json=flightsList,proto3" json:"flights_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearestFlightsResponse) Reset() {
	*x = NearestFlightsResponse{}
	mi := &file_fr24_proto__nearest_flights_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearestFlightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearestFlightsResponse) ProtoMessage() {}

func (x *NearestFlightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fr24_proto__nearest_flights_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearestFlightsResponse.ProtoReflect.Descriptor instead.
func (*NearestFlightsResponse) Descriptor() ([]byte, []int) {
	return file_fr24_proto__nearest_flights_proto_rawDescGZIP(), []int{3}
}

func (x *NearestFlightsResponse) GetFlightsList() []*NearbyFlight {
	if x != nil {
		return x.FlightsList
	}
	return nil
}

var File_fr24_proto__nearest_flights_proto protoreflect.FileDescriptor

const file_fr24_proto__nearest_flights_proto_rawDesc = "" +
	"\n" +
	"!fr24/proto/_nearest_flights.proto\x12\x10fr24.feed.api.v1\x1a\x18fr24/proto/_common.proto\"1\n" +
	"\vGeolocation\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x02R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x02R\x03lon\"\x80\x01\n" +
	"\x15NearestFlightsRequest\x129\n" +
	"\blocation\x18\x01 \x01(\v2\x1d.fr24.feed.api.v1.GeolocationR\blocation\x12\x16\n" +
	"\x06radius\x18\x02 \x01(\rR\x06radius\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"S\n" +
	"\fNearbyFlight\x12'\n" +
	"\x06flight\x18\x01 \x01(\v2\x0f._common.FlightR\x06flight\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\rR\bdistance\"[\n" +
	"\x16NearestFlightsResponse\x12A\n" +
	"\fflights_list\x18\x01 \x03(\v2\x1e.fr24.feed.api.v1.NearbyFlightR\vflightsListB0Z.github.com/igolaizola/flightradar24/fr24/protob\x06proto3"

var (
	file_fr24_proto__nearest_flights_proto_rawDescOnce sync.Once
	file_fr24_proto__nearest_flights_proto_rawDescData []byte
)

func file_fr24_proto__nearest_flights_proto_rawDescGZIP() []byte {
	file_fr24_proto__nearest_flights_proto_rawDescOnce.Do(func() {
		file_fr24_proto__nearest_flights_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fr24_proto__nearest_flights_proto_rawDesc), len(file_fr24_proto__nearest_flights_proto_rawDesc)))
	})
	return file_fr24_proto__nearest_flights_proto_rawDescData
}

var file_fr24_proto__nearest_flights_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_fr24_proto__nearest_flights_proto_goTypes = []any{
	(*Geolocation)(nil),            // 0: fr24.feed.api.v1.Geolocation
	(*NearestFlightsRequest)(nil),  // 1: fr24.feed.api.v1.NearestFlightsRequest
	(*NearbyFlight)(nil),           // 2: fr24.feed.api.v1.NearbyFlight
	(*NearestFlightsResponse)(nil), // 3: fr24.feed.api.v1.NearestFlightsResponse
	(*Flight)(nil),                 // 4: _common.Flight
}
var file_fr24_proto__nearest_flights_proto_depIdxs = []int32{
	0, // 0: fr24.feed.api.v1.NearestFlightsRequest.location:type_name -> fr24.feed.api.v1.Geolocation
	4, // 1: fr24.feed.api.v1.NearbyFlight.flight:type_name -> _common.Flight
	2, // 2: fr24.feed.api.v1.NearestFlightsResponse.flights_list:type_name -> fr24.feed.api.v1.NearbyFlight
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_fr24_proto__nearest_flights_proto_init() }
func file_fr24_proto__nearest_flights_proto_init() {
	if File_fr24_proto__nearest_flights_proto != nil {
		return
	}
	file_fr24_proto__common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fr24_proto__nearest_flights_proto_rawDesc), len(file_fr24_proto__nearest_flights_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fr24_proto__nearest_flights_proto_goTypes,
		DependencyIndexes: file_fr24_proto__nearest_flights_proto_depIdxs,
		MessageInfos:      file_fr24_proto__nearest_flights_proto_msgTypes,
	}.Build()
	File_fr24_proto__nearest_flights_proto = out.File
	file_fr24_proto__nearest_flights_proto_goTypes = nil
	file_fr24_proto__nearest_flights_proto_depIdxs = nil
}
