// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.3
// source: pkg/proto/_playback_flight.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlaybackFlightRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	FlightId uint32                 `protobuf:"fixed32,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"` // FR24 Flight ID (e.g. `962788562` = `0x3962fcd2`)
	// Actual time of departure (ATD) of the historic flight,
	// Unix timestamp in seconds.
	Timestamp       uint64                `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RestrictionMode RestrictionVisibility `protobuf:"varint,3,opt,name=restriction_mode,json=restrictionMode,proto3,enum=_common.RestrictionVisibility" json:"restriction_mode,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlaybackFlightRequest) Reset() {
	*x = PlaybackFlightRequest{}
	mi := &file_fr24_proto__playback_flight_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaybackFlightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaybackFlightRequest) ProtoMessage() {}

func (x *PlaybackFlightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fr24_proto__playback_flight_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaybackFlightRequest.ProtoReflect.Descriptor instead.
func (*PlaybackFlightRequest) Descriptor() ([]byte, []int) {
	return file_fr24_proto__playback_flight_proto_rawDescGZIP(), []int{0}
}

func (x *PlaybackFlightRequest) GetFlightId() uint32 {
	if x != nil {
		return x.FlightId
	}
	return 0
}

func (x *PlaybackFlightRequest) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PlaybackFlightRequest) GetRestrictionMode() RestrictionVisibility {
	if x != nil {
		return x.RestrictionMode
	}
	return RestrictionVisibility_NOT_VISIBLE
}

type PlaybackFlightResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AircraftInfo    *AircraftInfo          `protobuf:"bytes,1,opt,name=aircraft_info,json=aircraftInfo,proto3" json:"aircraft_info,omitempty"`
	ScheduleInfo    *ScheduleInfo          `protobuf:"bytes,2,opt,name=schedule_info,json=scheduleInfo,proto3" json:"schedule_info,omitempty"`
	FlightInfo      *ExtendedFlightInfo    `protobuf:"bytes,3,opt,name=flight_info,json=flightInfo,proto3" json:"flight_info,omitempty"`
	FlightTrailList []*TrailPoint          `protobuf:"bytes,4,rep,name=flight_trail_list,json=flightTrailList,proto3" json:"flight_trail_list,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlaybackFlightResponse) Reset() {
	*x = PlaybackFlightResponse{}
	mi := &file_fr24_proto__playback_flight_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaybackFlightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaybackFlightResponse) ProtoMessage() {}

func (x *PlaybackFlightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fr24_proto__playback_flight_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaybackFlightResponse.ProtoReflect.Descriptor instead.
func (*PlaybackFlightResponse) Descriptor() ([]byte, []int) {
	return file_fr24_proto__playback_flight_proto_rawDescGZIP(), []int{1}
}

func (x *PlaybackFlightResponse) GetAircraftInfo() *AircraftInfo {
	if x != nil {
		return x.AircraftInfo
	}
	return nil
}

func (x *PlaybackFlightResponse) GetScheduleInfo() *ScheduleInfo {
	if x != nil {
		return x.ScheduleInfo
	}
	return nil
}

func (x *PlaybackFlightResponse) GetFlightInfo() *ExtendedFlightInfo {
	if x != nil {
		return x.FlightInfo
	}
	return nil
}

func (x *PlaybackFlightResponse) GetFlightTrailList() []*TrailPoint {
	if x != nil {
		return x.FlightTrailList
	}
	return nil
}

var File_fr24_proto__playback_flight_proto protoreflect.FileDescriptor

const file_fr24_proto__playback_flight_proto_rawDesc = "" +
	"\n" +
	"!fr24/proto/_playback_flight.proto\x12\x10fr24.feed.api.v1\x1a\x18fr24/proto/_common.proto\"\x9d\x01\n" +
	"\x15PlaybackFlightRequest\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\aR\bflightId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12I\n" +
	"\x10restriction_mode\x18\x03 \x01(\x0e2\x1e._common.RestrictionVisibilityR\x0frestrictionMode\"\x8f\x02\n" +
	"\x16PlaybackFlightResponse\x12:\n" +
	"\raircraft_info\x18\x01 \x01(\v2\x15._common.AircraftInfoR\faircraftInfo\x12:\n" +
	"\rschedule_info\x18\x02 \x01(\v2\x15._common.ScheduleInfoR\fscheduleInfo\x12<\n" +
	"\vflight_info\x18\x03 \x01(\v2\x1b._common.ExtendedFlightInfoR\n" +
	"flightInfo\x12?\n" +
	"\x11flight_trail_list\x18\x04 \x03(\v2\x13._common.TrailPointR\x0fflightTrailListB0Z.github.com/igolaizola/flightradar24/fr24/protob\x06proto3"

var (
	file_fr24_proto__playback_flight_proto_rawDescOnce sync.Once
	file_fr24_proto__playback_flight_proto_rawDescData []byte
)

func file_fr24_proto__playback_flight_proto_rawDescGZIP() []byte {
	file_fr24_proto__playback_flight_proto_rawDescOnce.Do(func() {
		file_fr24_proto__playback_flight_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fr24_proto__playback_flight_proto_rawDesc), len(file_fr24_proto__playback_flight_proto_rawDesc)))
	})
	return file_fr24_proto__playback_flight_proto_rawDescData
}

var file_fr24_proto__playback_flight_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fr24_proto__playback_flight_proto_goTypes = []any{
	(*PlaybackFlightRequest)(nil),  // 0: fr24.feed.api.v1.PlaybackFlightRequest
	(*PlaybackFlightResponse)(nil), // 1: fr24.feed.api.v1.PlaybackFlightResponse
	(RestrictionVisibility)(0),     // 2: _common.RestrictionVisibility
	(*AircraftInfo)(nil),           // 3: _common.AircraftInfo
	(*ScheduleInfo)(nil),           // 4: _common.ScheduleInfo
	(*ExtendedFlightInfo)(nil),     // 5: _common.ExtendedFlightInfo
	(*TrailPoint)(nil),             // 6: _common.TrailPoint
}
var file_fr24_proto__playback_flight_proto_depIdxs = []int32{
	2, // 0: fr24.feed.api.v1.PlaybackFlightRequest.restriction_mode:type_name -> _common.RestrictionVisibility
	3, // 1: fr24.feed.api.v1.PlaybackFlightResponse.aircraft_info:type_name -> _common.AircraftInfo
	4, // 2: fr24.feed.api.v1.PlaybackFlightResponse.schedule_info:type_name -> _common.ScheduleInfo
	5, // 3: fr24.feed.api.v1.PlaybackFlightResponse.flight_info:type_name -> _common.ExtendedFlightInfo
	6, // 4: fr24.feed.api.v1.PlaybackFlightResponse.flight_trail_list:type_name -> _common.TrailPoint
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_fr24_proto__playback_flight_proto_init() }
func file_fr24_proto__playback_flight_proto_init() {
	if File_fr24_proto__playback_flight_proto != nil {
		return
	}
	file_fr24_proto__common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fr24_proto__playback_flight_proto_rawDesc), len(file_fr24_proto__playback_flight_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fr24_proto__playback_flight_proto_goTypes,
		DependencyIndexes: file_fr24_proto__playback_flight_proto_depIdxs,
		MessageInfos:      file_fr24_proto__playback_flight_proto_msgTypes,
	}.Build()
	File_fr24_proto__playback_flight_proto = out.File
	file_fr24_proto__playback_flight_proto_goTypes = nil
	file_fr24_proto__playback_flight_proto_depIdxs = nil
}
