// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.3
// source: pkg/proto/_top_flights.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FollowedFlight struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FlightId        uint32                 `protobuf:"varint,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`                      // FR24 Flight ID (e.g. `962709904` = `0x3961c990`)
	LiveClicks      uint32                 `protobuf:"varint,2,opt,name=live_clicks,json=liveClicks,proto3" json:"live_clicks,omitempty"`                // Number of live clicks/views (e.g. `1212`)
	TotalClicks     uint32                 `protobuf:"varint,3,opt,name=total_clicks,json=totalClicks,proto3" json:"total_clicks,omitempty"`             // Total number of clicks/views (e.g. `6128`)
	FlightNumber    string                 `protobuf:"bytes,4,opt,name=flight_number,json=flightNumber,proto3" json:"flight_number,omitempty"`           // Flight number (e.g. `"EK261"`)
	Callsign        string                 `protobuf:"bytes,5,opt,name=callsign,proto3" json:"callsign,omitempty"`                                       // Callsign (e.g. `"UAE261"`)
	Squawk          uint32                 `protobuf:"varint,6,opt,name=squawk,proto3" json:"squawk,omitempty"`                                          // Squawk code (e.g. `4032` = `0o7700`)
	FromIata        string                 `protobuf:"bytes,7,opt,name=from_iata,json=fromIata,proto3" json:"from_iata,omitempty"`                       // IATA code of origin airport (e.g. `"DXB"`)
	FromCity        string                 `protobuf:"bytes,8,opt,name=from_city,json=fromCity,proto3" json:"from_city,omitempty"`                       // City name of origin airport (e.g. `"Dubai"`)
	ToIata          string                 `protobuf:"bytes,9,opt,name=to_iata,json=toIata,proto3" json:"to_iata,omitempty"`                             // IATA code of destination airport (e.g. `"GRU"`)
	ToCity          string                 `protobuf:"bytes,10,opt,name=to_city,json=toCity,proto3" json:"to_city,omitempty"`                            // City name of destination airport (e.g. `"Sao Paulo"`)
	Type            string                 `protobuf:"bytes,11,opt,name=type,proto3" json:"type,omitempty"`                                              // Aircraft type code (e.g. `"A388"`)
	FullDescription string                 `protobuf:"bytes,12,opt,name=full_description,json=fullDescription,proto3" json:"full_description,omitempty"` // Full aircraft description (e.g. `"Airbus A380-861"`)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FollowedFlight) Reset() {
	*x = FollowedFlight{}
	mi := &file_fr24_proto__top_flights_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowedFlight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowedFlight) ProtoMessage() {}

func (x *FollowedFlight) ProtoReflect() protoreflect.Message {
	mi := &file_fr24_proto__top_flights_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowedFlight.ProtoReflect.Descriptor instead.
func (*FollowedFlight) Descriptor() ([]byte, []int) {
	return file_fr24_proto__top_flights_proto_rawDescGZIP(), []int{0}
}

func (x *FollowedFlight) GetFlightId() uint32 {
	if x != nil {
		return x.FlightId
	}
	return 0
}

func (x *FollowedFlight) GetLiveClicks() uint32 {
	if x != nil {
		return x.LiveClicks
	}
	return 0
}

func (x *FollowedFlight) GetTotalClicks() uint32 {
	if x != nil {
		return x.TotalClicks
	}
	return 0
}

func (x *FollowedFlight) GetFlightNumber() string {
	if x != nil {
		return x.FlightNumber
	}
	return ""
}

func (x *FollowedFlight) GetCallsign() string {
	if x != nil {
		return x.Callsign
	}
	return ""
}

func (x *FollowedFlight) GetSquawk() uint32 {
	if x != nil {
		return x.Squawk
	}
	return 0
}

func (x *FollowedFlight) GetFromIata() string {
	if x != nil {
		return x.FromIata
	}
	return ""
}

func (x *FollowedFlight) GetFromCity() string {
	if x != nil {
		return x.FromCity
	}
	return ""
}

func (x *FollowedFlight) GetToIata() string {
	if x != nil {
		return x.ToIata
	}
	return ""
}

func (x *FollowedFlight) GetToCity() string {
	if x != nil {
		return x.ToCity
	}
	return ""
}

func (x *FollowedFlight) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FollowedFlight) GetFullDescription() string {
	if x != nil {
		return x.FullDescription
	}
	return ""
}

type TopFlightsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"` // 1..=10
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopFlightsRequest) Reset() {
	*x = TopFlightsRequest{}
	mi := &file_fr24_proto__top_flights_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopFlightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopFlightsRequest) ProtoMessage() {}

func (x *TopFlightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fr24_proto__top_flights_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopFlightsRequest.ProtoReflect.Descriptor instead.
func (*TopFlightsRequest) Descriptor() ([]byte, []int) {
	return file_fr24_proto__top_flights_proto_rawDescGZIP(), []int{1}
}

func (x *TopFlightsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TopFlightsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ScoreboardList []*FollowedFlight      `protobuf:"bytes,1,rep,name=scoreboard_list,json=scoreboardList,proto3" json:"scoreboard_list,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TopFlightsResponse) Reset() {
	*x = TopFlightsResponse{}
	mi := &file_fr24_proto__top_flights_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopFlightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopFlightsResponse) ProtoMessage() {}

func (x *TopFlightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fr24_proto__top_flights_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopFlightsResponse.ProtoReflect.Descriptor instead.
func (*TopFlightsResponse) Descriptor() ([]byte, []int) {
	return file_fr24_proto__top_flights_proto_rawDescGZIP(), []int{2}
}

func (x *TopFlightsResponse) GetScoreboardList() []*FollowedFlight {
	if x != nil {
		return x.ScoreboardList
	}
	return nil
}

var File_fr24_proto__top_flights_proto protoreflect.FileDescriptor

const file_fr24_proto__top_flights_proto_rawDesc = "" +
	"\n" +
	"\x1dfr24/proto/_top_flights.proto\x12\x10fr24.feed.api.v1\"\xf5\x02\n" +
	"\x0eFollowedFlight\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\rR\bflightId\x12\x1f\n" +
	"\vlive_clicks\x18\x02 \x01(\rR\n" +
	"liveClicks\x12!\n" +
	"\ftotal_clicks\x18\x03 \x01(\rR\vtotalClicks\x12#\n" +
	"\rflight_number\x18\x04 \x01(\tR\fflightNumber\x12\x1a\n" +
	"\bcallsign\x18\x05 \x01(\tR\bcallsign\x12\x16\n" +
	"\x06squawk\x18\x06 \x01(\rR\x06squawk\x12\x1b\n" +
	"\tfrom_iata\x18\a \x01(\tR\bfromIata\x12\x1b\n" +
	"\tfrom_city\x18\b \x01(\tR\bfromCity\x12\x17\n" +
	"\ato_iata\x18\t \x01(\tR\x06toIata\x12\x17\n" +
	"\ato_city\x18\n" +
	" \x01(\tR\x06toCity\x12\x12\n" +
	"\x04type\x18\v \x01(\tR\x04type\x12)\n" +
	"\x10full_description\x18\f \x01(\tR\x0ffullDescription\")\n" +
	"\x11TopFlightsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\"_\n" +
	"\x12TopFlightsResponse\x12I\n" +
	"\x0fscoreboard_list\x18\x01 \x03(\v2 .fr24.feed.api.v1.FollowedFlightR\x0escoreboardListB0Z.github.com/igolaizola/flightradar24/fr24/protob\x06proto3"

var (
	file_fr24_proto__top_flights_proto_rawDescOnce sync.Once
	file_fr24_proto__top_flights_proto_rawDescData []byte
)

func file_fr24_proto__top_flights_proto_rawDescGZIP() []byte {
	file_fr24_proto__top_flights_proto_rawDescOnce.Do(func() {
		file_fr24_proto__top_flights_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fr24_proto__top_flights_proto_rawDesc), len(file_fr24_proto__top_flights_proto_rawDesc)))
	})
	return file_fr24_proto__top_flights_proto_rawDescData
}

var file_fr24_proto__top_flights_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_fr24_proto__top_flights_proto_goTypes = []any{
	(*FollowedFlight)(nil),     // 0: fr24.feed.api.v1.FollowedFlight
	(*TopFlightsRequest)(nil),  // 1: fr24.feed.api.v1.TopFlightsRequest
	(*TopFlightsResponse)(nil), // 2: fr24.feed.api.v1.TopFlightsResponse
}
var file_fr24_proto__top_flights_proto_depIdxs = []int32{
	0, // 0: fr24.feed.api.v1.TopFlightsResponse.scoreboard_list:type_name -> fr24.feed.api.v1.FollowedFlight
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fr24_proto__top_flights_proto_init() }
func file_fr24_proto__top_flights_proto_init() {
	if File_fr24_proto__top_flights_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fr24_proto__top_flights_proto_rawDesc), len(file_fr24_proto__top_flights_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fr24_proto__top_flights_proto_goTypes,
		DependencyIndexes: file_fr24_proto__top_flights_proto_depIdxs,
		MessageInfos:      file_fr24_proto__top_flights_proto_msgTypes,
	}.Build()
	File_fr24_proto__top_flights_proto = out.File
	file_fr24_proto__top_flights_proto_goTypes = nil
	file_fr24_proto__top_flights_proto_depIdxs = nil
}
