// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.3
// source: pkg/proto/v1.proto

package proto

import (
	reflect "reflect"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_fr24_proto_v1_proto protoreflect.FileDescriptor

const file_fr24_proto_v1_proto_rawDesc = "" +
	"\n" +
	"\x13fr24/proto/v1.proto\x12\x10fr24.feed.api.v1\x1a\x18fr24/proto/_common.proto\x1a\x1bfr24/proto/_live_feed.proto\x1a\x18fr24/proto/_health.proto\x1a!fr24/proto/_nearest_flights.proto\x1a$fr24/proto/_live_flight_status.proto\x1a$fr24/proto/_fetch_search_index.proto\x1a\x1ffr24/proto/_follow_flight.proto\x1a\x1dfr24/proto/_top_flights.proto\x1a\x1cfr24/proto/_live_trail.proto\x1a fr24/proto/_historic_trail.proto\x1a fr24/proto/_flight_details.proto\x1a!fr24/proto/_playback_flight.proto2\x8c\t\n" +
	"\x04Feed\x126\n" +
	"\x04Echo\x12\x16.fr24.feed.api.v1.Ping\x1a\x16.fr24.feed.api.v1.Pong\x12/\n" +
	"\tCountDown\x12\x11._common.Duration\x1a\r._common.Tick0\x01\x12Q\n" +
	"\bLiveFeed\x12!.fr24.feed.api.v1.LiveFeedRequest\x1a\".fr24.feed.api.v1.LiveFeedResponse\x12Q\n" +
	"\bPlayback\x12!.fr24.feed.api.v1.PlaybackRequest\x1a\".fr24.feed.api.v1.PlaybackResponse\x12c\n" +
	"\x0eNearestFlights\x12'.fr24.feed.api.v1.NearestFlightsRequest\x1a(.fr24.feed.api.v1.NearestFlightsResponse\x12l\n" +
	"\x11LiveFlightsStatus\x12*.fr24.feed.api.v1.LiveFlightsStatusRequest\x1a+.fr24.feed.api.v1.LiveFlightsStatusResponse\x12i\n" +
	"\x10FetchSearchIndex\x12).fr24.feed.api.v1.FetchSearchIndexRequest\x1a*.fr24.feed.api.v1.FetchSearchIndexResponse\x12_\n" +
	"\fFollowFlight\x12%.fr24.feed.api.v1.FollowFlightRequest\x1a&.fr24.feed.api.v1.FollowFlightResponse0\x01\x12W\n" +
	"\n" +
	"TopFlights\x12#.fr24.feed.api.v1.TopFlightsRequest\x1a$.fr24.feed.api.v1.TopFlightsResponse\x12T\n" +
	"\tLiveTrail\x12\".fr24.feed.api.v1.LiveTrailRequest\x1a#.fr24.feed.api.v1.LiveTrailResponse\x12`\n" +
	"\rHistoricTrail\x12&.fr24.feed.api.v1.HistoricTrailRequest\x1a'.fr24.feed.api.v1.HistoricTrailResponse\x12`\n" +
	"\rFlightDetails\x12&.fr24.feed.api.v1.FlightDetailsRequest\x1a'.fr24.feed.api.v1.FlightDetailsResponse\x12c\n" +
	"\x0ePlaybackFlight\x12'.fr24.feed.api.v1.PlaybackFlightRequest\x1a(.fr24.feed.api.v1.PlaybackFlightResponseB2H\x01Z.github.com/igolaizola/flightradar24/fr24/protoP\x00P\x01P\x02P\x03P\x04P\x05P\x06P\aP\bP\tP\n" +
	"P\vb\x06proto3"

var file_fr24_proto_v1_proto_goTypes = []any{
	(*Ping)(nil),                      // 0: fr24.feed.api.v1.Ping
	(*Duration)(nil),                  // 1: _common.Duration
	(*LiveFeedRequest)(nil),           // 2: fr24.feed.api.v1.LiveFeedRequest
	(*PlaybackRequest)(nil),           // 3: fr24.feed.api.v1.PlaybackRequest
	(*NearestFlightsRequest)(nil),     // 4: fr24.feed.api.v1.NearestFlightsRequest
	(*LiveFlightsStatusRequest)(nil),  // 5: fr24.feed.api.v1.LiveFlightsStatusRequest
	(*FetchSearchIndexRequest)(nil),   // 6: fr24.feed.api.v1.FetchSearchIndexRequest
	(*FollowFlightRequest)(nil),       // 7: fr24.feed.api.v1.FollowFlightRequest
	(*TopFlightsRequest)(nil),         // 8: fr24.feed.api.v1.TopFlightsRequest
	(*LiveTrailRequest)(nil),          // 9: fr24.feed.api.v1.LiveTrailRequest
	(*HistoricTrailRequest)(nil),      // 10: fr24.feed.api.v1.HistoricTrailRequest
	(*FlightDetailsRequest)(nil),      // 11: fr24.feed.api.v1.FlightDetailsRequest
	(*PlaybackFlightRequest)(nil),     // 12: fr24.feed.api.v1.PlaybackFlightRequest
	(*Pong)(nil),                      // 13: fr24.feed.api.v1.Pong
	(*Tick)(nil),                      // 14: _common.Tick
	(*LiveFeedResponse)(nil),          // 15: fr24.feed.api.v1.LiveFeedResponse
	(*PlaybackResponse)(nil),          // 16: fr24.feed.api.v1.PlaybackResponse
	(*NearestFlightsResponse)(nil),    // 17: fr24.feed.api.v1.NearestFlightsResponse
	(*LiveFlightsStatusResponse)(nil), // 18: fr24.feed.api.v1.LiveFlightsStatusResponse
	(*FetchSearchIndexResponse)(nil),  // 19: fr24.feed.api.v1.FetchSearchIndexResponse
	(*FollowFlightResponse)(nil),      // 20: fr24.feed.api.v1.FollowFlightResponse
	(*TopFlightsResponse)(nil),        // 21: fr24.feed.api.v1.TopFlightsResponse
	(*LiveTrailResponse)(nil),         // 22: fr24.feed.api.v1.LiveTrailResponse
	(*HistoricTrailResponse)(nil),     // 23: fr24.feed.api.v1.HistoricTrailResponse
	(*FlightDetailsResponse)(nil),     // 24: fr24.feed.api.v1.FlightDetailsResponse
	(*PlaybackFlightResponse)(nil),    // 25: fr24.feed.api.v1.PlaybackFlightResponse
}
var file_fr24_proto_v1_proto_depIdxs = []int32{
	0,  // 0: fr24.feed.api.v1.Feed.Echo:input_type -> fr24.feed.api.v1.Ping
	1,  // 1: fr24.feed.api.v1.Feed.CountDown:input_type -> _common.Duration
	2,  // 2: fr24.feed.api.v1.Feed.LiveFeed:input_type -> fr24.feed.api.v1.LiveFeedRequest
	3,  // 3: fr24.feed.api.v1.Feed.Playback:input_type -> fr24.feed.api.v1.PlaybackRequest
	4,  // 4: fr24.feed.api.v1.Feed.NearestFlights:input_type -> fr24.feed.api.v1.NearestFlightsRequest
	5,  // 5: fr24.feed.api.v1.Feed.LiveFlightsStatus:input_type -> fr24.feed.api.v1.LiveFlightsStatusRequest
	6,  // 6: fr24.feed.api.v1.Feed.FetchSearchIndex:input_type -> fr24.feed.api.v1.FetchSearchIndexRequest
	7,  // 7: fr24.feed.api.v1.Feed.FollowFlight:input_type -> fr24.feed.api.v1.FollowFlightRequest
	8,  // 8: fr24.feed.api.v1.Feed.TopFlights:input_type -> fr24.feed.api.v1.TopFlightsRequest
	9,  // 9: fr24.feed.api.v1.Feed.LiveTrail:input_type -> fr24.feed.api.v1.LiveTrailRequest
	10, // 10: fr24.feed.api.v1.Feed.HistoricTrail:input_type -> fr24.feed.api.v1.HistoricTrailRequest
	11, // 11: fr24.feed.api.v1.Feed.FlightDetails:input_type -> fr24.feed.api.v1.FlightDetailsRequest
	12, // 12: fr24.feed.api.v1.Feed.PlaybackFlight:input_type -> fr24.feed.api.v1.PlaybackFlightRequest
	13, // 13: fr24.feed.api.v1.Feed.Echo:output_type -> fr24.feed.api.v1.Pong
	14, // 14: fr24.feed.api.v1.Feed.CountDown:output_type -> _common.Tick
	15, // 15: fr24.feed.api.v1.Feed.LiveFeed:output_type -> fr24.feed.api.v1.LiveFeedResponse
	16, // 16: fr24.feed.api.v1.Feed.Playback:output_type -> fr24.feed.api.v1.PlaybackResponse
	17, // 17: fr24.feed.api.v1.Feed.NearestFlights:output_type -> fr24.feed.api.v1.NearestFlightsResponse
	18, // 18: fr24.feed.api.v1.Feed.LiveFlightsStatus:output_type -> fr24.feed.api.v1.LiveFlightsStatusResponse
	19, // 19: fr24.feed.api.v1.Feed.FetchSearchIndex:output_type -> fr24.feed.api.v1.FetchSearchIndexResponse
	20, // 20: fr24.feed.api.v1.Feed.FollowFlight:output_type -> fr24.feed.api.v1.FollowFlightResponse
	21, // 21: fr24.feed.api.v1.Feed.TopFlights:output_type -> fr24.feed.api.v1.TopFlightsResponse
	22, // 22: fr24.feed.api.v1.Feed.LiveTrail:output_type -> fr24.feed.api.v1.LiveTrailResponse
	23, // 23: fr24.feed.api.v1.Feed.HistoricTrail:output_type -> fr24.feed.api.v1.HistoricTrailResponse
	24, // 24: fr24.feed.api.v1.Feed.FlightDetails:output_type -> fr24.feed.api.v1.FlightDetailsResponse
	25, // 25: fr24.feed.api.v1.Feed.PlaybackFlight:output_type -> fr24.feed.api.v1.PlaybackFlightResponse
	13, // [13:26] is the sub-list for method output_type
	0,  // [0:13] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_fr24_proto_v1_proto_init() }
func file_fr24_proto_v1_proto_init() {
	if File_fr24_proto_v1_proto != nil {
		return
	}
	file_fr24_proto__common_proto_init()
	file_fr24_proto__live_feed_proto_init()
	file_fr24_proto__health_proto_init()
	file_fr24_proto__nearest_flights_proto_init()
	file_fr24_proto__live_flight_status_proto_init()
	file_fr24_proto__fetch_search_index_proto_init()
	file_fr24_proto__follow_flight_proto_init()
	file_fr24_proto__top_flights_proto_init()
	file_fr24_proto__live_trail_proto_init()
	file_fr24_proto__historic_trail_proto_init()
	file_fr24_proto__flight_details_proto_init()
	file_fr24_proto__playback_flight_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fr24_proto_v1_proto_rawDesc), len(file_fr24_proto_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fr24_proto_v1_proto_goTypes,
		DependencyIndexes: file_fr24_proto_v1_proto_depIdxs,
	}.Build()
	File_fr24_proto_v1_proto = out.File
	file_fr24_proto_v1_proto_goTypes = nil
	file_fr24_proto_v1_proto_depIdxs = nil
}
